### ISSUE TITLE
Skipping sections of docs when run under certain Python versions

### ISSUE THREAD

**Issue by pauleveritt** [cjw296/sybil#10]
I have a section of docs which use variable annotations: https://github.com/pauleveritt/wired/tree/dataclasses_tutorial/docs/tutorials/dcdi

The `index.rst` has a skip at the top. However, simply parsing the file under Python 3.5 causes a `SyntaxError`. I need to teach the Sybil collector to skip it.

I tried putting a `conftest.py` in that directory which sniffs the Python interpreter version and does an exclude. However, It seems to augment the Sybil instance, not replace it.

**Comment by cjw296** [comment]
Oh, interesting, is it the whole file you want to skip?

So, the "augment versus replace" is pytest behaviour, sybil is using a test discovery plugin for pytest, I have to admit, I didn't realise it'd work quite like it is. What happens if you put `docs/tutorials/dcdi/*` in `excludes`?

This is another interesting problem, codeblock could defer compilation until execution time?

**Comment by pauleveritt** [comment]
Adding it to excludes sounds like a good idea, but alas, doesn't do the trick.

**Comment by cjw296** [comment]
Yeah, I think you'd need to speak to @nicoddemus and friends over at pytest to figure out the exclude part.

I've implemented the "late compilation" approach in 7932cbfef34f66f9c995d354507dddd373ede778 and released it in 1.2.0.

**Comment by pauleveritt** [comment]
Thanks!

**Comment by nicoddemus** [comment]
Since 4.4 `pytest.skip()` can be used inside doctests to dynamically skip them, but I'm not sure if this will help here, as you will probably have trouble collecting the test in the first place...

**Comment by cjw296** [comment]
@nicoddemus - yeah, sybil has its own skip mechanism now: https://sybil.readthedocs.io/en/latest/parsers.html#skip

I was mistaken on the pytest part too, looks like the choice to filter on filename rather than full path was one I made here: https://github.com/cjw296/sybil/blob/master/sybil/integration/pytest.py#L116

If that needs to change in the future, I'll address it "next time" ;-)

**Comment by nicoddemus** [comment]
Thanks!

I'm making some changes to the pytest docs, I'll make sure to put a blurb about Sybil. 👍

**Comment by cjw296** [comment]
Thanks! I'm happy to help anyone who wants to use it to test examples in documentation :-)

**Comment by nicoddemus** [comment]
I will open a PR shortly, would appreciate if you have a few minutes to review it. 😁

**Comment by cjw296** [comment]
Certainly!

**Comment by nicoddemus** [comment]
PR open: https://github.com/pytest-dev/pytest/pull/5183 👍
